### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by LucasLauDev** [joshterrill/freewhois#4]
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise 
which was not handled with .catch(). The promise rejected with the reason "Error making WHOIS request for domain: https://example.com/".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by joshterrill** [comment]
I am not able to reproduce this problem. I'll need you to share more about how you're using the program. When I run "freewhois https://example.com/" from my command line, it works fine. See screenshot.

![Screen Shot 2021-01-31 at 1 00 13 AM](https://user-images.githubusercontent.com/5368757/106379286-b4207100-635f-11eb-8ca3-b9ca7b2f3aa1.png)

**Comment by joshterrill** [comment]
@LauTHong I'm going to close this issue out as I cannot reproduce the issue and haven't heard a response from you in a few weeks. If this issue persists, please provide me with the exact command that you're running and the version of freewhois that you are using. If you can provide these and I can get to a reproducible issue, I will reopen the ticket and fix whatever needs to be fixed.
